global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'email-me'
  routes:
    - receiver: 'email-me'
      group_wait: 10s
      match_re:
        severity: critical
      continue: true

receivers:
  - name: 'email-me'
    email_configs:
    - to: mail_for_some_people@mail.ru
      from: alerts@mail.ru
      smarthost: smtp.mail.ru:587
      auth_username: "alerts@mail.ru"
      auth_identity: "alerts@mail.ru"
      auth_password: "Password"
      send_resolved: true
